services:
  reconned-instagram:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AUTH_TOKEN=${AUTH_TOKEN:-secret_token}
    restart: unless-stopped
